[package]
name = "gethype"
version = "0.1.0"
authors = ["ashtneoi <ashtneoi@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
hyper = "0.12.14"
futures = "0.1.25"

[dependencies.curly]
path = "../curly"
